### ISSUE TITLE
version 1.0.9 missing in github

### ISSUE THREAD

**Issue by terefang** [RPTools/upnplib#5]
maptool uses version 1.0.9

but this repository only has 1.0.7

please update so i can start contributing a fix i need

**Comment by Azhrei** [comment]
I don't have a reference for 1.0.9.  If you ca point me to it, I'll investigate.

**Comment by terefang** [comment]
https://github.com/RPTools/maptool/blob/main/build.gradle#L215

**Comment by terefang** [comment]
as far as i can say it got commited on the initial move to gradle 6 years ago

**Comment by Azhrei** [comment]
Per the Discord conversation, this appears to be the latest version.  I did find some additional changes in a local branch (dated Apr 23rd 2013) that had not been pushed, so I just did that.

All the more reason to find a different library to use, something more up to date and that we don't have to maintain.  (Portmapper is still an option, if you have time to integrate a new library instead of trying to fix this one?)
